# ---- Simple linear regression ----

- name: "simple_pymc3_100"
  model: "SIMPLE_PYMC3"
  mem: "3000"
  time: "00:30:00"
  config:
    size: 100

- name: "simple_pymc3_1000"
  model: "SIMPLE_PYMC3"
  mem: "8000"
  time: "00:30:00"
  config:
    size: 1000

- name: "simple_pymc3_10000"
  model: "SIMPLE_PYMC3"
  mem: "10000"
  time: "01:00:00"
  config:
    size: 10000

- name: "simple_pymc3_100000"
  model: "SIMPLE_PYMC3"
  mem: "30000"
  time: "02:00:00"
  config:
    size: 100000

- name: "simple_pymc3_1000000"
  model: "SIMPLE_PYMC3"
  mem: "80000"
  time: "12:00:00"
  config:
    size: 1000000

- name: "simple_stan_100"
  model: "SIMPLE_STAN"
  mem: "4000"
  time: "00:15:00"
  config:
    size: 100

- name: "simple_stan_1000"
  model: "SIMPLE_STAN"
  mem: "4000"
  time: "00:30:00"
  config:
    size: 1000

- name: "simple_stan_10000"
  model: "SIMPLE_STAN"
  mem: "8000"
  time: "00:45:00"
  config:
    size: 10000

- name: "simple_stan_100000"
  model: "SIMPLE_STAN"
  mem: "32000"
  time: "02:00:00"
  config:
    size: 100000

- name: "simple_stan_1000000"
  model: "SIMPLE_STAN"
  mem: "32000"
  time: "12:00:00"
  config:
    size: 1000000

# ---- Hierarchical model ----

- name: "hierarchical_pymc3_10-5-2"
  model: "HIERARCHICAL_PYMC3"
  mem: "4000"
  time: "00:15:00"
  config:
    N: 10
    J: 5
    K: 2

- name: "hierarchical_stan_10-5-2"
  model: "HIERARCHICAL_STAN"
  mem: "4000"
  time: "00:15:00"
  config:
    N: 10
    J: 5
    K: 2

- name: "hierarchical_pymc3_10-10-2"
  model: "HIERARCHICAL_PYMC3"
  mem: "8000"
  time: "00:45:00"
  config:
    N: 10
    J: 10
    K: 2

- name: "hierarchical_stan_10-10-2"
  model: "HIERARCHICAL_STAN"
  mem: "8000"
  time: "00:45:00"
  config:
    N: 10
    J: 10
    K: 2

- name: "hierarchical_pymc3_10-10-5"
  model: "HIERARCHICAL_PYMC3"
  mem: "16000"
  time: "02:00:00"
  config:
    N: 10
    J: 10
    K: 5

- name: "hierarchical_stan_10-10-5"
  model: "HIERARCHICAL_STAN"
  mem: "16000"
  time: "02:00:00"
  config:
    N: 10
    J: 10
    K: 5

- name: "hierarchical_pymc3_10-50-2"
  model: "HIERARCHICAL_PYMC3"
  mem: "32000"
  time: "03:00:00"
  config:
    N: 10
    J: 50
    K: 2

- name: "hierarchical_stan_10-50-2"
  model: "HIERARCHICAL_STAN"
  mem: "32000"
  time: "03:00:00"
  config:
    N: 10
    J: 50
    K: 2

- name: "hierarchical_pymc3_10-100-5"
  model: "HIERARCHICAL_PYMC3"
  mem: "32000"
  time: "05:00:00"
  config:
    N: 10
    J: 100
    K: 5

- name: "hierarchical_stan_10-100-5"
  model: "HIERARCHICAL_STAN"
  mem: "32000"
  time: "05:00:00"
  config:
    N: 10
    J: 100
    K: 5

- name: "hierarchical_pymc3_10-1000-5"
  model: "HIERARCHICAL_PYMC3"
  mem: "32000"
  time: "08:00:00"
  config:
    N: 10
    J: 1000
    K: 5

- name: "hierarchical_stan_10-1000-5"
  model: "HIERARCHICAL_STAN"
  mem: "32000"
  time: "08:00:00"
  config:
    N: 10
    J: 1000
    K: 5

- name: "hierarchical_pymc3_10-10000-5"
  model: "HIERARCHICAL_PYMC3"
  mem: "64000"
  time: "12:00:00"
  config:
    N: 10
    J: 10000
    K: 5

- name: "hierarchical_stan_10-10000-5"
  model: "HIERARCHICAL_STAN"
  mem: "64000"
  time: "48:00:00"
  partition: "medium"
  config:
    N: 10
    J: 10000
    K: 5

# ---- Negative binomial model ----

- name: "negbinom_pymc3_10-1"
  model: "NEGBINOM_PYMC3"
  mem: "4000"
  time: "00:10:00"
  config:
    N: 10
    alpha: 1.0

- name: "negbinom_stan_10-1"
  model: "NEGBINOM_STAN"
  mem: "4000"
  time: "00:10:00"
  config:
    N: 10
    alpha: 1.0
