# ---- Simple linear regression ----

- name: "simple_pymc3_100"
  model: "SIMPLE_PYMC3"
  mem: "3000"
  time: "00:30:00"
  config:
    size: 100
    tune: 1000
    draws: 1000

- name: "simple_pymc3_1000"
  model: "SIMPLE_PYMC3"
  mem: "8000"
  time: "00:30:00"
  config:
    size: 1000
    tune: 1000
    draws: 1000

- name: "simple_pymc3_10000"
  model: "SIMPLE_PYMC3"
  mem: "10000"
  time: "01:00:00"
  config:
    size: 10000
    tune: 1000
    draws: 1000

- name: "simple_pymc3_100000"
  model: "SIMPLE_PYMC3"
  mem: "30000"
  time: "02:00:00"
  config:
    size: 100000
    tune: 1000
    draws: 1000

- name: "simple_pymc3_1000000"
  model: "SIMPLE_PYMC3"
  mem: "64000"
  time: "08:00:00"
  config:
    size: 1000000
    tune: 1000
    draws: 1000

- name: "simple_stan_100"
  model: "SIMPLE_STAN"
  mem: "4000"
  time: "00:15:00"
  config:
    size: 100
    tune: 1000
    draws: 1000

- name: "simple_stan_1000"
  model: "SIMPLE_STAN"
  mem: "4000"
  time: "00:30:00"
  config:
    size: 1000
    tune: 1000
    draws: 1000

- name: "simple_stan_10000"
  model: "SIMPLE_STAN"
  mem: "8000"
  time: "00:45:00"
  config:
    size: 10000
    tune: 1000
    draws: 1000

- name: "simple_stan_100000"
  model: "SIMPLE_STAN"
  mem: "32000"
  time: "02:00:00"
  config:
    size: 100000
    tune: 1000
    draws: 1000

- name: "simple_stan_1000000"
  model: "SIMPLE_STAN"
  mem: "64000"
  time: "05:00:00"
  config:
    size: 1000000
    tune: 1000
    draws: 1000

# ---- Hierarchical model ----

- name: "hierarchical_pymc3_10-5-2"
  model: "HIERARCHICAL_PYMC3"
  mem: "4000"
  time: "00:15:00"
  config:
    N: 10
    J: 5
    K: 2
    tune: 1000
    draws: 1000

- name: "hierarchical_stan_10-5-2"
  model: "HIERARCHICAL_STAN"
  mem: "4000"
  time: "00:15:00"
  config:
    N: 10
    J: 5
    K: 2
    tune: 1000
    draws: 1000

- name: "hierarchical_pymc3_10-10-2"
  model: "HIERARCHICAL_PYMC3"
  mem: "8000"
  time: "00:45:00"
  config:
    N: 10
    J: 10
    K: 2
    tune: 1000
    draws: 1000

- name: "hierarchical_stan_10-10-2"
  model: "HIERARCHICAL_STAN"
  mem: "8000"
  time: "00:45:00"
  config:
    N: 10
    J: 10
    K: 2
    tune: 1000
    draws: 1000

- name: "hierarchical_pymc3_10-10-5"
  model: "HIERARCHICAL_PYMC3"
  mem: "16000"
  time: "02:00:00"
  config:
    N: 10
    J: 10
    K: 5
    tune: 1000
    draws: 1000

- name: "hierarchical_stan_10-10-5"
  model: "HIERARCHICAL_STAN"
  mem: "16000"
  time: "02:00:00"
  config:
    N: 10
    J: 10
    K: 5
    tune: 1000
    draws: 1000

- name: "hierarchical_pymc3_10-50-2"
  model: "HIERARCHICAL_PYMC3"
  mem: "32000"
  time: "03:00:00"
  config:
    N: 10
    J: 50
    K: 2
    tune: 1000
    draws: 1000

- name: "hierarchical_stan_10-50-2"
  model: "HIERARCHICAL_STAN"
  mem: "32000"
  time: "03:00:00"
  config:
    N: 10
    J: 50
    K: 2
    tune: 1000
    draws: 1000
