__default__:
  partition: "short"
  cores: 4
  out: "logs/%j_{rule}.log"
  err: "logs/%j_{rule}.log"
  mail: "NONE"
fit_model:
  mem: "{params.mem}"
  time: "{params.time}"
  partition: "{params.partition}"
  J: "{wildcards.name}"
